split_strategy:
  cutoffs:
    train_end: null
    valid_end: null
  mode: proportions
  order_column_preference:
  - transaction_timestamp
  - step
  - transaction_order
  - source_row_number
  proportions:
    test: 0.15
    train: 0.7
    valid: 0.15
  transaction_id_preference:
  - current_transaction_id
  - transaction_id
  - event_id
  - payment_id
