// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/transaction.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FraudProcessor_ProcessTransaction_FullMethodName = "/fraud.FraudProcessor/ProcessTransaction"
)

// FraudProcessorClient is the client API for FraudProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudProcessorClient interface {
	ProcessTransaction(ctx context.Context, in *TransactionEvent, opts ...grpc.CallOption) (*TransactionResponse, error)
}

type fraudProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudProcessorClient(cc grpc.ClientConnInterface) FraudProcessorClient {
	return &fraudProcessorClient{cc}
}

func (c *fraudProcessorClient) ProcessTransaction(ctx context.Context, in *TransactionEvent, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, FraudProcessor_ProcessTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudProcessorServer is the server API for FraudProcessor service.
// All implementations must embed UnimplementedFraudProcessorServer
// for forward compatibility
type FraudProcessorServer interface {
	ProcessTransaction(context.Context, *TransactionEvent) (*TransactionResponse, error)
	mustEmbedUnimplementedFraudProcessorServer()
}

// UnimplementedFraudProcessorServer must be embedded to have forward compatible implementations.
type UnimplementedFraudProcessorServer struct {
}

func (UnimplementedFraudProcessorServer) ProcessTransaction(context.Context, *TransactionEvent) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTransaction not implemented")
}
func (UnimplementedFraudProcessorServer) mustEmbedUnimplementedFraudProcessorServer() {}

// UnsafeFraudProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudProcessorServer will
// result in compilation errors.
type UnsafeFraudProcessorServer interface {
	mustEmbedUnimplementedFraudProcessorServer()
}

func RegisterFraudProcessorServer(s grpc.ServiceRegistrar, srv FraudProcessorServer) {
	s.RegisterService(&FraudProcessor_ServiceDesc, srv)
}

func _FraudProcessor_ProcessTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudProcessorServer).ProcessTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudProcessor_ProcessTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudProcessorServer).ProcessTransaction(ctx, req.(*TransactionEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudProcessor_ServiceDesc is the grpc.ServiceDesc for FraudProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.FraudProcessor",
	HandlerType: (*FraudProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTransaction",
			Handler:    _FraudProcessor_ProcessTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction.proto",
}
